export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const GET_ERRORS = 'GET_ERRORS';
export const CURRENT_USER = 'CURRENT_USER';
export const LOADING = 'LOADING';
export const PROFILE_NOT_LOADING = 'PROFILE_NOT_LOADING';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_PROFILES_INFO = 'GET_PROFILES_INFO';